<<<<<<< HEAD
=======
<<<<<<< HEAD
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "SMK Prestasi Prima",
  description: "Website Resmi SMK Prestasi Prima",
=======
>>>>>>> dev
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
<<<<<<< HEAD
=======
>>>>>>> 6488c37 (First commit)
>>>>>>> dev
};

export default function RootLayout({
  children,
<<<<<<< HEAD
=======
<<<<<<< HEAD
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body className={poppins.className}>{children}</body>
=======
>>>>>>> dev
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
<<<<<<< HEAD
=======
>>>>>>> 6488c37 (First commit)
>>>>>>> dev
    </html>
  );
}
